"""Visualize how initial tangential velocity selects a Keplerian conic.

The body starts at radius ``r0`` with zero radial velocity, so whenever its
tangential speed is at least the local circular speed, the starting point is
periapsis. This calls ``orbitworks.analytical.classify_orbit`` to turn that
initial state into orbital elements and ``orbitworks.geometry.sample_conic``
to sample the resulting shape, rather than re-deriving Binet's-equation
constants and polar-orbit sampling locally. Those same functions also back
``orbitworks.app``, so this script and the app share one tested
implementation. The four selected speeds produce a circle, ellipse, parabola,
and hyperbola around Earth.
"""

from math import sqrt
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle

from orbitworks import analytical, geometry
from orbitworks.constants import MU_EARTH, R_EARTH
from orbitworks.graphics_mpl import set_plot_options

# User configuration.
GRAVITATIONAL_PARAMETER = MU_EARTH
CENTRAL_BODY_RADIUS = R_EARTH
INITIAL_RADIUS = 4.0 * R_EARTH
MAXIMUM_PLOTTED_RADIUS = 6.0 * INITIAL_RADIUS
NUMBER_OF_POINTS = 2_000
SHOW_FIGURE = True
FIGURE_PATH = None  # For example: "conic_sections.png"

# Tangential speed relative to the circular speed at INITIAL_RADIUS, with zero
# radial speed. Since v0 >= vc places the body at periapsis, the ratio alone
# selects the conic type:
CONIC_CASES = (
    ("Circle", 1.0),
    ("Ellipse", sqrt(1.5)),
    ("Parabola", sqrt(2.0)),
    ("Hyperbola", sqrt(2.5)),
)


class ConicCase:
    """Store the initial tangential speed and classified elements of one case."""

    def __init__(self, name, speed_ratio, initial_speed, elements):
        self.name = name
        self.speed_ratio = speed_ratio
        self.initial_speed = initial_speed
        self.elements = elements


def conic_case_from_tangential_speed(name, speed_ratio):
    """Classify the conic selected by an initial tangential speed at periapsis.

    Zero radial speed at ``INITIAL_RADIUS`` places the body at periapsis
    whenever ``speed_ratio >= 1``, so ``orbitworks.analytical.classify_orbit``
    infers the same conic that Binet's equation predicts analytically.
    """
    circular_speed = sqrt(GRAVITATIONAL_PARAMETER / INITIAL_RADIUS)
    initial_speed = speed_ratio * circular_speed
    if initial_speed < circular_speed:
        raise ValueError("The initial point is periapsis only when v0 >= vc.")

    position = np.array([INITIAL_RADIUS, 0.0])
    velocity = np.array([0.0, initial_speed])
    elements = analytical.classify_orbit(position, velocity, GRAVITATIONAL_PARAMETER)
    return ConicCase(name, speed_ratio, initial_speed, elements)


def sample_case(case):
    """Sample the conic for one case, truncating open branches for plotting.

    Closed conics are sampled through a complete revolution. Parabolic and
    hyperbolic radii diverge at their asymptotes, so their plotted branches
    are truncated at ``MAXIMUM_PLOTTED_RADIUS``.
    """
    elements = case.elements
    angle_limit = None
    if not elements.is_bound:
        angle_limit = geometry.angle_limit_for_radius(
            elements.eccentricity, elements.semi_latus_rectum, MAXIMUM_PLOTTED_RADIUS
        )
    return geometry.sample_conic(elements, angle_limit=angle_limit, num_points=NUMBER_OF_POINTS)


def print_case_table(cases):
    """Display how each chosen velocity produces energy, eccentricity, and p."""
    print(
        f"{'orbit':<11} {'v0/vc':>8} {'v0 [km/s]':>12} "
        f"{'energy [MJ/kg]':>15} {'e':>8} {'p/r0':>9}"
    )
    for case in cases:
        elements = case.elements
        print(
            f"{case.name:<11} "
            f"{case.speed_ratio:8.4f} "
            f"{case.initial_speed / 1e3:12.4f} "
            f"{elements.specific_energy / 1e6:15.4f} "
            f"{elements.eccentricity:8.4f} "
            f"{elements.semi_latus_rectum / INITIAL_RADIUS:9.4f}"
        )


def create_figure():
    """Plot the four orbit classes generated by the configured velocities."""
    cases = [
        conic_case_from_tangential_speed(name, speed_ratio) for name, speed_ratio in CONIC_CASES
    ]
    print_case_table(cases)

    set_plot_options()
    figure, axes = plt.subplots(2, 2, figsize=(10, 9), constrained_layout=True)

    for axes_item, case in zip(axes.flat, cases, strict=True):
        path = sample_case(case) / INITIAL_RADIUS
        axes_item.plot(path[:, 0], path[:, 1], linewidth=2.0)
        axes_item.add_patch(
            Circle(
                (0.0, 0.0),
                CENTRAL_BODY_RADIUS / INITIAL_RADIUS,
                color="#4C78A8",
                alpha=0.75,
                label="Earth",
            )
        )
        axes_item.scatter(
            [1.0],
            [0.0],
            marker="o",
            color="#E45756",
            zorder=3,
            label="initial point",
        )
        axes_item.set_aspect("equal", adjustable="datalim")
        axes_item.set_xlabel(r"$x/r_0$")
        axes_item.set_ylabel(r"$y/r_0$")
        axes_item.set_title(
            rf"{case.name}: $e={case.elements.eccentricity:.1f}$, "
            rf"$v_0/v_c={case.speed_ratio:.3f}$"
        )

    axes[0, 0].legend(loc="upper right")
    figure.suptitle(
        "The initial tangential speed selects the conic section",
        fontsize=14,
    )
    return figure


def main():
    """Run the conic-section experiment using the top-level configuration."""
    figure = create_figure()

    if FIGURE_PATH is not None:
        figure_path = Path(FIGURE_PATH)
        figure_path.parent.mkdir(parents=True, exist_ok=True)
        figure.savefig(figure_path, dpi=200, bbox_inches="tight")
        print(f"Saved figure to {figure_path}")

    if SHOW_FIGURE:
        plt.show()


if __name__ == "__main__":
    main()
